<a href="https://colab.research.google.com/github/Shiva8164/Forest-Fire/blob/main/Forest_Fires.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

In [ ]:
Forest_data = pd.read_csv('/content/forestfires.csv')

In [ ]:
Forest_data.shape

(517, 31)

In [ ]:
Forest_data.head()

,month,day,FFMC,DMC,DC,ISI,temp,RH,wind,rain,...,monthfeb,monthjan,monthjul,monthjun,monthmar,monthmay,monthnov,monthoct,monthsep,size_category
0,mar,fri,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,...,0,0,0,0,1,0,0,0,0,small
1,oct,tue,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,...,0,0,0,0,0,0,0,1,0,small
2,oct,sat,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,...,0,0,0,0,0,0,0,1,0,small
3,mar,fri,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,...,0,0,0,0,1,0,0,0,0,small
4,mar,sun,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,...,0,0,0,0,1,0,0,0,0,small

In [ ]:
Forest_data.pop('month')
Forest_data.head()

,day,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area,...,monthfeb,monthjan,monthjul,monthjun,monthmar,monthmay,monthnov,monthoct,monthsep,size_category
0,fri,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,0.0,...,0,0,0,0,1,0,0,0,0,small
1,tue,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,0.0,...,0,0,0,0,0,0,0,1,0,small
2,sat,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,0.0,...,0,0,0,0,0,0,0,1,0,small
3,fri,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,0.0,...,0,0,0,0,1,0,0,0,0,small
4,sun,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,0.0,...,0,0,0,0,1,0,0,0,0,small

In [ ]:
Forest_data.pop('day')
Forest_data.head()

,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area,dayfri,...,monthfeb,monthjan,monthjul,monthjun,monthmar,monthmay,monthnov,monthoct,monthsep,size_category
0,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,0.0,1,...,0,0,0,0,1,0,0,0,0,small
1,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,0.0,0,...,0,0,0,0,0,0,0,1,0,small
2,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,0.0,0,...,0,0,0,0,0,0,0,1,0,small
3,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,0.0,1,...,0,0,0,0,1,0,0,0,0,small
4,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,0.0,0,...,0,0,0,0,1,0,0,0,0,small

In [ ]:
Forest_data.isnull().sum()

FFMC             0
DMC              0
DC               0
ISI              0
temp             0
RH               0
wind             0
rain             0
area             0
dayfri           0
daymon           0
daysat           0
daysun           0
daythu           0
daytue           0
daywed           0
monthapr         0
monthaug         0
monthdec         0
monthfeb         0
monthjan         0
monthjul         0
monthjun         0
monthmar         0
monthmay         0
monthnov         0
monthoct         0
monthsep         0
size_category    0
dtype: int64

In [ ]:
label_encode = LabelEncoder()
label = label_encode.fit_transform(Forest_data.size_category)
Forest_data['target'] = label
forest_data = Forest_data.drop(columns = 'size_category', axis = 1)
forest_data.head()

,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area,dayfri,...,monthfeb,monthjan,monthjul,monthjun,monthmar,monthmay,monthnov,monthoct,monthsep,target
0,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,0.0,1,...,0,0,0,0,1,0,0,0,0,1
1,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,0.0,0,...,0,0,0,0,0,0,0,1,0,1
2,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,0.0,0,...,0,0,0,0,0,0,0,1,0,1
3,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,0.0,1,...,0,0,0,0,1,0,0,0,0,1
4,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,0.0,0,...,0,0,0,0,1,0,0,0,0,1

In [ ]:
x = forest_data.iloc[:,0:28]
x.head()

,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area,dayfri,...,monthdec,monthfeb,monthjan,monthjul,monthjun,monthmar,monthmay,monthnov,monthoct,monthsep
0,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,0.0,1,...,0,0,0,0,0,1,0,0,0,0
1,90.6,35.4,669.1,6.7,18.0,33,0.9,0.0,0.0,0,...,0,0,0,0,0,0,0,0,1,0
2,90.6,43.7,686.9,6.7,14.6,33,1.3,0.0,0.0,0,...,0,0,0,0,0,0,0,0,1,0
3,91.7,33.3,77.5,9.0,8.3,97,4.0,0.2,0.0,1,...,0,0,0,0,0,1,0,0,0,0
4,89.3,51.3,102.2,9.6,11.4,99,1.8,0.0,0.0,0,...,0,0,0,0,0,1,0,0,0,0

In [ ]:
y = forest_data.iloc[:,28]
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)
x_test.head()

,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area,dayfri,...,monthdec,monthfeb,monthjan,monthjul,monthjun,monthmar,monthmay,monthnov,monthoct,monthsep
213,87.6,52.2,103.8,5.0,11.0,46,5.8,0.0,27.35,0,...,0,0,0,0,0,1,0,0,0,0
435,90.8,84.7,376.6,5.6,23.8,51,1.8,0.0,0.00,0,...,0,0,0,1,0,0,0,0,0,0
343,91.5,130.1,807.1,7.5,15.9,51,4.5,0.0,2.18,0,...,0,0,0,0,0,0,0,0,0,1
230,92.9,133.3,699.6,9.2,26.4,21,4.5,0.0,88.49,0,...,0,0,0,0,0,0,0,0,0,1
171,85.6,90.4,609.6,6.6,17.4,50,4.0,0.0,2.69,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
sc = StandardScaler()
sc.fit(x_train, y_train)

StandardScaler()

In [ ]:
model = Sequential()

In [ ]:
model.add(Dense(units = 10, activation = 'relu', kernel_initializer = 'he_uniform', input_dim = 28))
model.add(Dense(units = 8, activation = 'relu', kernel_initializer = 'he_uniform'))
model.add(Dense(units = 1, activation = 'sigmoid', kernel_initializer = 'glorot_uniform'))

In [ ]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [ ]:
model.fit(x, y, batch_size = 10, epochs = 200, validation_split = 0.33)

Epoch 1/200
35/35 [==============================] - 0s 7ms/step - loss: 0.0190 - accuracy: 0.9913 - val_loss: 0.2383 - val_accuracy: 0.9474
Epoch 2/200
35/35 [==============================] - 0s 4ms/step - loss: 0.0659 - accuracy: 0.9798 - val_loss: 0.4167 - val_accuracy: 0.9181
Epoch 3/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0315 - accuracy: 0.9855 - val_loss: 0.5202 - val_accuracy: 0.8830
Epoch 4/200
35/35 [==============================] - 0s 4ms/step - loss: 0.0216 - accuracy: 0.9913 - val_loss: 0.3053 - val_accuracy: 0.9357
Epoch 5/200
35/35 [==============================] - 0s 6ms/step - loss: 0.0449 - accuracy: 0.9769 - val_loss: 0.0802 - val_accuracy: 0.9708
Epoch 6/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0253 - accuracy: 0.9884 - val_loss: 0.1022 - val_accuracy: 0.9649
Epoch 7/200
35/35 [==============================] - 0s 4ms/step - loss: 0.0223 - accuracy: 0.9913 - val_loss: 0.1330 - val_accuracy: 0.9591
Epoch 8/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0301 - accuracy: 0.9827 - val_loss: 0.1204 - val_accuracy: 0.9591
Epoch 9/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0146 - accuracy: 0.9971 - val_loss: 0.2033 - val_accuracy: 0.9532
Epoch 10/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0176 - accuracy: 0.9913 - val_loss: 0.2306 - val_accuracy: 0.9474
Epoch 11/200
35/35 [==============================] - 0s 4ms/step - loss: 0.0172 - accuracy: 0.9942 - val_loss: 0.2672 - val_accuracy: 0.9298
Epoch 12/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0207 - accuracy: 0.9855 - val_loss: 0.1890 - val_accuracy: 0.9649
Epoch 13/200
35/35 [==============================] - 0s 6ms/step - loss: 0.0139 - accuracy: 1.0000 - val_loss: 0.1467 - val_accuracy: 0.9649
Epoch 14/200
35/35 [==============================] - 0s 6ms/step - loss: 0.0181 - accuracy: 0.9971 - val_loss: 0.2315 - val_accuracy: 0.9415
Epoch 15/200
35/35 [==============================] - 0s 6ms/step - loss: 0.0144 - accuracy: 0.9971 - val_loss: 0.1948 - val_accuracy: 0.9649
Epoch 16/200
35/35 [==============================] - 0s 6ms/step - loss: 0.0155 - accuracy: 0.9942 - val_loss: 0.2046 - val_accuracy: 0.9532
Epoch 17/200
35/35 [==============================] - 0s 7ms/step - loss: 0.0173 - accuracy: 0.9913 - val_loss: 0.1863 - val_accuracy: 0.9708
Epoch 18/200
35/35 [==============================] - 0s 6ms/step - loss: 0.0156 - accuracy: 0.9942 - val_loss: 0.2174 - val_accuracy: 0.9532
Epoch 19/200
35/35 [==============================] - 0s 6ms/step - loss: 0.0151 - accuracy: 0.9971 - val_loss: 0.1973 - val_accuracy: 0.9591
Epoch 20/200
35/35 [==============================] - 0s 7ms/step - loss: 0.0203 - accuracy: 0.9913 - val_loss: 0.2230 - val_accuracy: 0.9474
Epoch 21/200
35/35 [==============================] - 0s 6ms/step - loss: 0.0185 - accuracy: 0.9913 - val_loss: 0.2604 - val_accuracy: 0.9357
Epoch 22/200
35/35 [==============================] - 0s 7ms/step - loss: 0.0171 - accuracy: 0.9971 - val_loss: 0.1928 - val_accuracy: 0.9591
Epoch 23/200
35/35 [==============================] - 0s 7ms/step - loss: 0.0214 - accuracy: 0.9884 - val_loss: 0.1183 - val_accuracy: 0.9649
Epoch 24/200
35/35 [==============================] - 0s 7ms/step - loss: 0.0222 - accuracy: 0.9913 - val_loss: 0.1556 - val_accuracy: 0.9708
Epoch 25/200
35/35 [==============================] - 0s 6ms/step - loss: 0.0155 - accuracy: 0.9942 - val_loss: 0.2433 - val_accuracy: 0.9357
Epoch 26/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0147 - accuracy: 0.9913 - val_loss: 0.1831 - val_accuracy: 0.9649
Epoch 27/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0233 - accuracy: 0.9855 - val_loss: 0.1343 - val_accuracy: 0.9649
Epoch 28/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0200 - accuracy: 0.9855 - val_loss: 0.3864 - val_accuracy: 0.9181
Epoch 29/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0140 - accuracy: 0.9971 - val_loss: 0.1879 - val_accuracy: 0.9532
Epoch 30/200
35/35 [==============================] - 0s 4ms/step - loss: 0.0144 - accuracy: 0.9971 - val_loss: 0.2601 - val_accuracy: 0.9298
Epoch 31/200
35/35 [==============================] - 0s 4ms/step - loss: 0.0212 - accuracy: 0.9942 - val_loss: 0.3209 - val_accuracy: 0.9298
Epoch 32/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0131 - accuracy: 0.9971 - val_loss: 0.3168 - val_accuracy: 0.9357
Epoch 33/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0130 - accuracy: 0.9971 - val_loss: 0.6297 - val_accuracy: 0.8772
Epoch 34/200
35/35 [==============================] - 0s 4ms/step - loss: 0.0219 - accuracy: 0.9913 - val_loss: 0.1541 - val_accuracy: 0.9649
Epoch 35/200
35/35 [==============================] - 0s 4ms/step - loss: 0.0288 - accuracy: 0.9855 - val_loss: 0.2176 - val_accuracy: 0.9532
Epoch 36/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0172 - accuracy: 0.9913 - val_loss: 0.1300 - val_accuracy: 0.9708
Epoch 37/200
35/35 [==============================] - 0s 4ms/step - loss: 0.0127 - accuracy: 0.9971 - val_loss: 0.1508 - val_accuracy: 0.9649
Epoch 38/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0133 - accuracy: 1.0000 - val_loss: 0.1360 - val_accuracy: 0.9649
Epoch 39/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0173 - accuracy: 0.9913 - val_loss: 0.0733 - val_accuracy: 0.9708
Epoch 40/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0163 - accuracy: 0.9942 - val_loss: 0.0789 - val_accuracy: 0.9708
Epoch 41/200
35/35 [==============================] - 0s 4ms/step - loss: 0.0516 - accuracy: 0.9827 - val_loss: 0.1708 - val_accuracy: 0.9649
Epoch 42/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0171 - accuracy: 0.9913 - val_loss: 0.1888 - val_accuracy: 0.9591
Epoch 43/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0184 - accuracy: 0.9913 - val_loss: 0.1515 - val_accuracy: 0.9649
Epoch 44/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0113 - accuracy: 0.9971 - val_loss: 0.3317 - val_accuracy: 0.9298
Epoch 45/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0384 - accuracy: 0.9855 - val_loss: 0.5446 - val_accuracy: 0.8947
Epoch 46/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0147 - accuracy: 0.9971 - val_loss: 0.1812 - val_accuracy: 0.9649
Epoch 47/200
35/35 [==============================] - 0s 4ms/step - loss: 0.0165 - accuracy: 0.9942 - val_loss: 0.4974 - val_accuracy: 0.9064
Epoch 48/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0326 - accuracy: 0.9855 - val_loss: 0.2395 - val_accuracy: 0.9532
Epoch 49/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0123 - accuracy: 1.0000 - val_loss: 0.1420 - val_accuracy: 0.9591
Epoch 50/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0151 - accuracy: 0.9971 - val_loss: 0.1187 - val_accuracy: 0.9649
Epoch 51/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0183 - accuracy: 0.9942 - val_loss: 0.2190 - val_accuracy: 0.9415
Epoch 52/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0094 - accuracy: 1.0000 - val_loss: 0.1224 - val_accuracy: 0.9649
Epoch 53/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0146 - accuracy: 0.9942 - val_loss: 0.1145 - val_accuracy: 0.9649
Epoch 54/200
35/35 [==============================] - 0s 4ms/step - loss: 0.0148 - accuracy: 0.9942 - val_loss: 0.1662 - val_accuracy: 0.9591
Epoch 55/200
35/35 [==============================] - 0s 6ms/step - loss: 0.0202 - accuracy: 0.9855 - val_loss: 0.0703 - val_accuracy: 0.9766
Epoch 56/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0157 - accuracy: 0.9942 - val_loss: 0.1671 - val_accuracy: 0.9649
Epoch 57/200
35/35 [==============================] - 0s 4ms/step - loss: 0.0124 - accuracy: 0.9971 - val_loss: 0.1056 - val_accuracy: 0.9649
Epoch 58/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0141 - accuracy: 0.9913 - val_loss: 0.0898 - val_accuracy: 0.9708
Epoch 59/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0336 - accuracy: 0.9855 - val_loss: 0.1035 - val_accuracy: 0.9649
Epoch 60/200
35/35 [==============================] - 0s 4ms/step - loss: 0.0166 - accuracy: 0.9942 - val_loss: 0.2531 - val_accuracy: 0.9474
Epoch 61/200
35/35 [==============================] - 0s 4ms/step - loss: 0.0304 - accuracy: 0.9884 - val_loss: 0.0908 - val_accuracy: 0.9649
Epoch 62/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0149 - accuracy: 0.9884 - val_loss: 0.0723 - val_accuracy: 0.9766
Epoch 63/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0171 - accuracy: 0.9942 - val_loss: 0.0760 - val_accuracy: 0.9649
Epoch 64/200
35/35 [==============================] - 0s 4ms/step - loss: 0.0138 - accuracy: 0.9913 - val_loss: 0.1142 - val_accuracy: 0.9591
Epoch 65/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0161 - accuracy: 0.9942 - val_loss: 0.1529 - val_accuracy: 0.9591
Epoch 66/200
35/35 [==============================] - 0s 4ms/step - loss: 0.0191 - accuracy: 0.9884 - val_loss: 0.1063 - val_accuracy: 0.9591
Epoch 67/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0106 - accuracy: 0.9971 - val_loss: 0.1171 - val_accuracy: 0.9649
Epoch 68/200
35/35 [==============================] - 0s 6ms/step - loss: 0.0117 - accuracy: 0.9971 - val_loss: 0.1059 - val_accuracy: 0.9649
Epoch 69/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0105 - accuracy: 1.0000 - val_loss: 0.0806 - val_accuracy: 0.9708
Epoch 70/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0140 - accuracy: 0.9942 - val_loss: 0.0982 - val_accuracy: 0.9649
Epoch 71/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0132 - accuracy: 0.9942 - val_loss: 0.1608 - val_accuracy: 0.9649
Epoch 72/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0142 - accuracy: 0.9942 - val_loss: 0.0918 - val_accuracy: 0.9649
Epoch 73/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0179 - accuracy: 0.9913 - val_loss: 0.1573 - val_accuracy: 0.9591
Epoch 74/200
35/35 [==============================] - 0s 6ms/step - loss: 0.0285 - accuracy: 0.9827 - val_loss: 0.1508 - val_accuracy: 0.9474
Epoch 75/200
35/35 [==============================] - 0s 4ms/step - loss: 0.0576 - accuracy: 0.9798 - val_loss: 0.0748 - val_accuracy: 0.9766
Epoch 76/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0189 - accuracy: 0.9913 - val_loss: 0.1032 - val_accuracy: 0.9649
Epoch 77/200
35/35 [==============================] - 0s 4ms/step - loss: 0.0124 - accuracy: 0.9942 - val_loss: 0.1599 - val_accuracy: 0.9649
Epoch 78/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0131 - accuracy: 0.9913 - val_loss: 0.1815 - val_accuracy: 0.9649
Epoch 79/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0115 - accuracy: 0.9971 - val_loss: 0.1592 - val_accuracy: 0.9591
Epoch 80/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0139 - accuracy: 0.9971 - val_loss: 0.1324 - val_accuracy: 0.9649
Epoch 81/200
35/35 [==============================] - 0s 4ms/step - loss: 0.0110 - accuracy: 0.9942 - val_loss: 0.1624 - val_accuracy: 0.9649
Epoch 82/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0189 - accuracy: 0.9884 - val_loss: 0.4062 - val_accuracy: 0.9240
Epoch 83/200
35/35 [==============================] - 0s 6ms/step - loss: 0.0201 - accuracy: 0.9942 - val_loss: 0.1076 - val_accuracy: 0.9649
Epoch 84/200
35/35 [==============================] - 0s 7ms/step - loss: 0.0164 - accuracy: 0.9913 - val_loss: 0.2777 - val_accuracy: 0.9474
Epoch 85/200
35/35 [==============================] - 0s 7ms/step - loss: 0.0131 - accuracy: 0.9971 - val_loss: 0.3107 - val_accuracy: 0.9415
Epoch 86/200
35/35 [==============================] - 0s 10ms/step - loss: 0.0157 - accuracy: 0.9884 - val_loss: 0.3443 - val_accuracy: 0.9357
Epoch 87/200
35/35 [==============================] - 0s 7ms/step - loss: 0.0063 - accuracy: 1.0000 - val_loss: 0.1155 - val_accuracy: 0.9649
Epoch 88/200
35/35 [==============================] - 0s 6ms/step - loss: 0.0156 - accuracy: 0.9942 - val_loss: 0.0993 - val_accuracy: 0.9591
Epoch 89/200
35/35 [==============================] - 0s 6ms/step - loss: 0.0150 - accuracy: 0.9884 - val_loss: 0.1871 - val_accuracy: 0.9649
Epoch 90/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0237 - accuracy: 0.9913 - val_loss: 0.3428 - val_accuracy: 0.9298
Epoch 91/200
35/35 [==============================] - 0s 6ms/step - loss: 0.0195 - accuracy: 0.9884 - val_loss: 0.0986 - val_accuracy: 0.9591
Epoch 92/200
35/35 [==============================] - 0s 6ms/step - loss: 0.0148 - accuracy: 0.9971 - val_loss: 0.1312 - val_accuracy: 0.9532
Epoch 93/200
35/35 [==============================] - 0s 7ms/step - loss: 0.0128 - accuracy: 0.9913 - val_loss: 0.1281 - val_accuracy: 0.9591
Epoch 94/200
35/35 [==============================] - 0s 4ms/step - loss: 0.0093 - accuracy: 0.9971 - val_loss: 0.1194 - val_accuracy: 0.9591
Epoch 95/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0082 - accuracy: 1.0000 - val_loss: 0.1764 - val_accuracy: 0.9591
Epoch 96/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0080 - accuracy: 0.9971 - val_loss: 0.1013 - val_accuracy: 0.9649
Epoch 97/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0184 - accuracy: 0.9942 - val_loss: 0.1494 - val_accuracy: 0.9591
Epoch 98/200
35/35 [==============================] - 0s 6ms/step - loss: 0.0087 - accuracy: 0.9971 - val_loss: 0.1501 - val_accuracy: 0.9649
Epoch 99/200
35/35 [==============================] - 0s 4ms/step - loss: 0.0103 - accuracy: 0.9942 - val_loss: 0.0684 - val_accuracy: 0.9766
Epoch 100/200
35/35 [==============================] - 0s 4ms/step - loss: 0.0143 - accuracy: 0.9942 - val_loss: 0.0582 - val_accuracy: 0.9825
Epoch 101/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0129 - accuracy: 0.9971 - val_loss: 0.0989 - val_accuracy: 0.9649
Epoch 102/200
35/35 [==============================] - 0s 4ms/step - loss: 0.0337 - accuracy: 0.9855 - val_loss: 0.0656 - val_accuracy: 0.9825
Epoch 103/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0135 - accuracy: 0.9942 - val_loss: 0.1278 - val_accuracy: 0.9591
Epoch 104/200
35/35 [==============================] - 0s 4ms/step - loss: 0.0129 - accuracy: 0.9971 - val_loss: 0.1434 - val_accuracy: 0.9649
Epoch 105/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0238 - accuracy: 0.9942 - val_loss: 0.0801 - val_accuracy: 0.9649
Epoch 106/200
35/35 [==============================] - 0s 4ms/step - loss: 0.0109 - accuracy: 0.9942 - val_loss: 0.1542 - val_accuracy: 0.9591
Epoch 107/200
35/35 [==============================] - 0s 4ms/step - loss: 0.0091 - accuracy: 0.9971 - val_loss: 0.1725 - val_accuracy: 0.9591
Epoch 108/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0069 - accuracy: 1.0000 - val_loss: 0.1663 - val_accuracy: 0.9591
Epoch 109/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0069 - accuracy: 0.9971 - val_loss: 0.1578 - val_accuracy: 0.9591
Epoch 110/200
35/35 [==============================] - 0s 4ms/step - loss: 0.0173 - accuracy: 0.9913 - val_loss: 0.1202 - val_accuracy: 0.9649
Epoch 111/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0995 - accuracy: 0.9740 - val_loss: 0.1052 - val_accuracy: 0.9649
Epoch 112/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0299 - accuracy: 0.9913 - val_loss: 0.1297 - val_accuracy: 0.9591
Epoch 113/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0083 - accuracy: 1.0000 - val_loss: 0.1219 - val_accuracy: 0.9591
Epoch 114/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0083 - accuracy: 0.9971 - val_loss: 0.0620 - val_accuracy: 0.9825
Epoch 115/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0255 - accuracy: 0.9884 - val_loss: 0.1758 - val_accuracy: 0.9591
Epoch 116/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0127 - accuracy: 0.9942 - val_loss: 0.0900 - val_accuracy: 0.9591
Epoch 117/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0148 - accuracy: 0.9913 - val_loss: 0.2523 - val_accuracy: 0.9532
Epoch 118/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0178 - accuracy: 0.9942 - val_loss: 0.1527 - val_accuracy: 0.9591
Epoch 119/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0182 - accuracy: 0.9913 - val_loss: 0.0925 - val_accuracy: 0.9591
Epoch 120/200
35/35 [==============================] - 0s 4ms/step - loss: 0.0083 - accuracy: 0.9971 - val_loss: 0.1621 - val_accuracy: 0.9591
Epoch 121/200
35/35 [==============================] - 0s 4ms/step - loss: 0.0408 - accuracy: 0.9798 - val_loss: 0.1665 - val_accuracy: 0.9591
Epoch 122/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0070 - accuracy: 0.9971 - val_loss: 0.0530 - val_accuracy: 0.9825
Epoch 123/200
35/35 [==============================] - 0s 4ms/step - loss: 0.0127 - accuracy: 0.9971 - val_loss: 0.0662 - val_accuracy: 0.9708
Epoch 124/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0126 - accuracy: 0.9913 - val_loss: 0.1023 - val_accuracy: 0.9591
Epoch 125/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0074 - accuracy: 1.0000 - val_loss: 0.0928 - val_accuracy: 0.9591
Epoch 126/200
35/35 [==============================] - 0s 4ms/step - loss: 0.0074 - accuracy: 0.9971 - val_loss: 0.1113 - val_accuracy: 0.9591
Epoch 127/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0074 - accuracy: 0.9942 - val_loss: 0.1065 - val_accuracy: 0.9649
Epoch 128/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0066 - accuracy: 0.9971 - val_loss: 0.0761 - val_accuracy: 0.9649
Epoch 129/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0074 - accuracy: 1.0000 - val_loss: 0.1222 - val_accuracy: 0.9591
Epoch 130/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0066 - accuracy: 0.9971 - val_loss: 0.1222 - val_accuracy: 0.9591
Epoch 131/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0091 - accuracy: 0.9971 - val_loss: 0.0684 - val_accuracy: 0.9766
Epoch 132/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0214 - accuracy: 0.9884 - val_loss: 0.1110 - val_accuracy: 0.9591
Epoch 133/200
35/35 [==============================] - 0s 4ms/step - loss: 0.0513 - accuracy: 0.9740 - val_loss: 0.0692 - val_accuracy: 0.9766
Epoch 134/200
35/35 [==============================] - 0s 4ms/step - loss: 0.0079 - accuracy: 0.9971 - val_loss: 0.1192 - val_accuracy: 0.9591
Epoch 135/200
35/35 [==============================] - 0s 6ms/step - loss: 0.0073 - accuracy: 0.9971 - val_loss: 0.1067 - val_accuracy: 0.9591
Epoch 136/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0069 - accuracy: 0.9971 - val_loss: 0.1226 - val_accuracy: 0.9591
Epoch 137/200
35/35 [==============================] - 0s 4ms/step - loss: 0.0147 - accuracy: 0.9913 - val_loss: 0.1141 - val_accuracy: 0.9591
Epoch 138/200
35/35 [==============================] - 0s 4ms/step - loss: 0.0236 - accuracy: 0.9913 - val_loss: 0.0777 - val_accuracy: 0.9766
Epoch 139/200
35/35 [==============================] - 0s 5ms/step - loss: 0.0366 - accuracy: 0.9884 - val_loss: 0.0579 - val_accuracy: 0.9825
Epoch 140/200
35/35 [==============================] - 0s 4ms/step - loss: 0.0063 - accuracy: 1.0000 - val_loss: 0.0838 - val_accuracy: 0.9591
Epoch 141/200

In [ ]:
y_prediction = model.predict(x_train)

13/13 [==============================] - 0s 2ms/step

In [ ]:
scores = model.evaluate(x_test, y_test)
print("%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

4/4 [==============================] - 0s 4ms/step - loss: 0.0700 - accuracy: 0.9712
accuracy: 97.12%

In [ ]:
input = (84.4,27.2,353.5,6.8,4.8,57,8.5,0,8.98,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0)
input_numpy = np.asarray(input)
input_reshape = input_numpy.reshape(1, -1)
prediction = model.predict(input_reshape)
print(prediction)
if prediction > 0.5:
  print('small')
elif prediction < 0.5:
  print('large')

1/1 [==============================] - 0s 23ms/step
[[0.02677521]]
large